LOCAL_INPUT_DIR: /path/to/dir/with/videos/
INPUT_BUCKET: name-of-s3-bucket
PRESET_ID: 1351620000001-100180 # eg FullHD108i50
PIPELINE_ID: 123456-abcdef # name of ElasticTranscoder pipeline to run
INPUT_FILE_FMT: .mp4
